CREATE TABLE albums (
    id TEXT PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  year INT NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  cover_url VARCHAR(255)
);
